# Generated by Django 3.2.9 on 2021-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_comment',
            new_name='GameComment',
        ),
    ]
