# Generated by Django 3.2.9 on 2023-10-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231002_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='societe',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('culture', 'culture'), ('sport', 'sport'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('visites', 'visites'), ('sorties', 'sorties'), ('coup de coeur', 'coup de coeur'), ('spectacles', 'spactacles')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('foot', 'foot'), ('lamb', 'lamb'), ('autres', 'autres'), ('tennis', 'tennis'), ('basket', 'basket')], max_length=250, null=True),
        ),
    ]
