# Generated by Django 3.2.9 on 2021-12-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_actu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
