# Generated by Django 3.2.9 on 2021-12-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_actu_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
