# Generated by Django 3.2.9 on 2023-10-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20231007_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('societe', 'societe'), ('culture', 'culture'), ('sport', 'sport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('spectacles', 'spactacles'), ('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('foot', 'foot'), ('lamb', 'lamb'), ('tennis', 'tennis'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
