# Generated by Django 3.2.9 on 2021-12-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_actu_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(blank=True, choices=[('sorties', 'sorties'), ('spectacles', 'spactacles'), ('visites', 'visites')], max_length=250, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='static')),
                ('author', models.CharField(max_length=255)),
                ('author_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
