# Generated by Django 3.2.9 on 2023-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20231007_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='FootPost',
        ),
        migrations.DeleteModel(
            name='GameComment',
        ),
        migrations.DeleteModel(
            name='Gaming',
        ),
        migrations.DeleteModel(
            name='Lamb',
        ),
        migrations.DeleteModel(
            name='Lamb_combat',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='body',
        ),
        migrations.AddField(
            model_name='sport',
            name='body1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='body3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='legende',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='legende2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='legende3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('culture', 'culture'), ('sport', 'sport'), ('activite', 'activite'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('lamb', 'lamb'), ('basket', 'basket'), ('foot', 'foot'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
