# Generated by Django 3.2.9 on 2021-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_activite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='video',
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('visites', 'visites'), ('spectacles', 'spactacles'), ('sorties', 'sorties')], max_length=250, null=True),
        ),
    ]
