# Generated by Django 3.2.9 on 2021-12-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211227_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamb_combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lutteur1', models.CharField(max_length=255)),
                ('lutteur2', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('sorties', 'sorties'), ('spectacles', 'spactacles'), ('visites', 'visites')], max_length=250, null=True),
        ),
    ]
