# Generated by Django 3.2.9 on 2023-10-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20231009_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_actu',
            name='actu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments_actu', to='home.actu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('culture', 'culture'), ('activite', 'activite'), ('societe', 'societe'), ('sport', 'sport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('spectacles', 'spactacles'), ('visites', 'visites'), ('sorties', 'sorties')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('lamb', 'lamb'), ('autres', 'autres'), ('basket', 'basket'), ('tennis', 'tennis'), ('foot', 'foot')], max_length=250, null=True),
        ),
    ]
