# Generated by Django 3.2.9 on 2022-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenements_Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('sorties', 'sorties'), ('visites', 'visites'), ('spectacles', 'spactacles')], max_length=250, null=True),
        ),
    ]
