# Generated by Django 3.2.9 on 2023-10-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20231009_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_actu',
            name='actu',
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('culture', 'culture'), ('sport', 'sport'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('visites', 'visites'), ('sorties', 'sorties'), ('spectacles', 'spactacles'), ('coup de coeur', 'coup de coeur')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('foot', 'foot'), ('tennis', 'tennis'), ('autres', 'autres'), ('lamb', 'lamb')], max_length=250, null=True),
        ),
    ]
