# Generated by Django 3.2.9 on 2023-10-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20231009_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_actu',
            name='actu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments_actu', to='home.actu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('societe', 'societe'), ('culture', 'culture'), ('sport', 'sport'), ('activite', 'activite')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('spectacles', 'spactacles'), ('visites', 'visites'), ('sorties', 'sorties'), ('coup de coeur', 'coup de coeur')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('lamb', 'lamb'), ('tennis', 'tennis'), ('autres', 'autres'), ('foot', 'foot'), ('basket', 'basket')], max_length=250, null=True),
        ),
    ]
