# Generated by Django 3.2.9 on 2023-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20231011_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('culture', 'culture'), ('activite', 'activite'), ('societe', 'societe'), ('sport', 'sport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('spectacles', 'spactacles'), ('visites', 'visites'), ('sorties', 'sorties')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('foot', 'foot'), ('lamb', 'lamb'), ('tennis', 'tennis'), ('autres', 'autres'), ('basket', 'basket')], max_length=250, null=True),
        ),
    ]
