# Generated by Django 3.2.9 on 2022-01-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220125_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('foot', 'foot'), ('lamb', 'lamb'), ('tennis', 'tennis'), ('autres', 'autres'), ('basket', 'basket')], max_length=250, null=True),
        ),
    ]
