# Generated by Django 3.2.9 on 2023-10-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20231011_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('culture', 'culture'), ('societe', 'societe'), ('sport', 'sport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('visites', 'visites'), ('spectacles', 'spactacles')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('autres', 'autres'), ('tennis', 'tennis'), ('foot', 'foot'), ('lamb', 'lamb')], max_length=250, null=True),
        ),
    ]
