# Generated by Django 3.2.9 on 2023-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20231011_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('spiritualite', 'spiritualite'), ('societe', 'societe'), ('culture', 'culture'), ('sport', 'sport'), ('monde', 'monde'), ('business', 'business'), ('politique', 'politique')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('sport', 'sport'), ('societe', 'societe'), ('activite', 'activite'), ('culture', 'culture')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('visites', 'visites'), ('sorties', 'sorties'), ('spectacles', 'spactacles')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('autres', 'autres'), ('tennis', 'tennis'), ('lamb', 'lamb'), ('foot', 'foot'), ('basket', 'basket')], max_length=250, null=True),
        ),
    ]
