# Generated by Django 3.2.9 on 2023-10-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20231012_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_politique',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.politique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('culture', 'culture'), ('sport', 'sport'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('spectacles', 'spactacles'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('monde', 'monde'), ('politique', 'politique'), ('business', 'business'), ('societe', 'societe'), ('culture', 'culture'), ('spiritualite', 'spiritualite'), ('sport', 'sport')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('autres', 'autres'), ('basket', 'basket'), ('foot', 'foot'), ('lamb', 'lamb')], max_length=250, null=True),
        ),
    ]
