# Generated by Django 3.2.9 on 2023-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20231013_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_politique',
            new_name='politique',
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('societe', 'societe'), ('sport', 'sport'), ('culture', 'culture')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('visites', 'visites'), ('spectacles', 'spactacles'), ('sorties', 'sorties')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('culture', 'culture'), ('politique', 'politique'), ('spiritualite', 'spiritualite'), ('business', 'business'), ('monde', 'monde'), ('societe', 'societe'), ('sport', 'sport')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('foot', 'foot'), ('autres', 'autres'), ('tennis', 'tennis'), ('lamb', 'lamb')], max_length=250, null=True),
        ),
    ]
