# Generated by Django 3.2.9 on 2022-01-29 12:55

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220129_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('tennis', 'tennis'), ('autres', 'autres'), ('lamb', 'lamb'), ('foot', 'foot')], max_length=250, null=True),
        ),
    ]
