# Generated by Django 3.2.9 on 2022-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220129_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='video',
            field=models.FileField(upload_to='video/%y'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('foot', 'foot'), ('basket', 'basket'), ('lamb', 'lamb'), ('autres', 'autres'), ('tennis', 'tennis')], max_length=250, null=True),
        ),
    ]
