# Generated by Django 3.2.9 on 2023-10-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20231013_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('culture', 'culture'), ('activite', 'activite'), ('sport', 'sport'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('spectacles', 'spactacles'), ('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('spiritualite', 'spiritualite'), ('business', 'business'), ('politique', 'politique'), ('monde', 'monde'), ('societe', 'societe'), ('culture', 'culture'), ('sport', 'sport')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='politique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_politique', to='home.politique'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('tennis', 'tennis'), ('foot', 'foot'), ('lamb', 'lamb'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
