# Generated by Django 3.2.9 on 2023-10-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20231013_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('sport', 'sport'), ('societe', 'societe'), ('activite', 'activite'), ('culture', 'culture')], max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('spiritualite', 'spiritualite'), ('politique', 'politique'), ('societe', 'societe'), ('sport', 'sport'), ('business', 'business'), ('monde', 'monde'), ('culture', 'culture')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='politique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.politique'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('lamb', 'lamb'), ('autres', 'autres'), ('basket', 'basket'), ('foot', 'foot')], max_length=250, null=True),
        ),
    ]
