# Generated by Django 3.2.9 on 2023-10-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20231013_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author_image',
        ),
        migrations.AddField(
            model_name='articles',
            name='videoLink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('culture', 'culture'), ('societe', 'societe'), ('sport', 'sport'), ('activite', 'activite')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('spectacles', 'spactacles'), ('coup de coeur', 'coup de coeur'), ('visites', 'visites'), ('sorties', 'sorties')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('sport', 'sport'), ('activite', 'activite'), ('business', 'business'), ('societe', 'societe'), ('international', 'international'), ('politique', 'politique'), ('spiritualite', 'spiritualite'), ('evenement', 'evenement'), ('video', 'video'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('culture', 'culture'), ('actualite', 'actualite'), ('breaking', 'breaking')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('basket', 'basket'), ('autres', 'autres'), ('lamb', 'lamb'), ('foot', 'foot')], max_length=250, null=True),
        ),
    ]
