# Generated by Django 3.2.9 on 2023-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20231014_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('culture', 'culture'), ('sport', 'sport'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('spectacles', 'spactacles'), ('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('international', 'international'), ('spiritualite', 'spiritualite'), ('actualite', 'actualite'), ('video', 'video'), ('breaking', 'breaking'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('culture', 'culture'), ('politique', 'politique'), ('evenement', 'evenement'), ('activite', 'activite'), ('business', 'business'), ('societe', 'societe'), ('sport', 'sport')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('lamb', 'lamb'), ('foot', 'foot'), ('autres', 'autres'), ('basket', 'basket')], max_length=250, null=True),
        ),
    ]
