# Generated by Django 3.2.9 on 2022-01-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20220130_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_voir',
            name='video',
        ),
        migrations.AddField(
            model_name='a_voir',
            name='videoLink',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('visites', 'visites'), ('spectacles', 'spactacles'), ('sorties', 'sorties')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('foot', 'foot'), ('tennis', 'tennis'), ('lamb', 'lamb'), ('basket', 'basket'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
