# Generated by Django 3.2.9 on 2022-01-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20220130_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('societe', 'societe'), ('culture', 'culture'), ('activite', 'activite'), ('sport', 'sport')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('basket', 'basket'), ('lamb', 'lamb'), ('foot', 'foot'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
