# Generated by Django 3.2.9 on 2022-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220201_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('societe', 'societe'), ('activite', 'activite'), ('sport', 'sport'), ('culture', 'culture')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('foot', 'foot'), ('autres', 'autres'), ('tennis', 'tennis'), ('lamb', 'lamb')], max_length=250, null=True),
        ),
    ]
