# Generated by Django 3.2.9 on 2023-10-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20231020_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('societe', 'societe'), ('activite', 'activite'), ('sport', 'sport'), ('culture', 'culture')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('spectacles', 'spactacles'), ('sorties', 'sorties'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('culture', 'culture'), ('activite', 'activite'), ('sport', 'sport'), ('breaking', 'breaking'), ('actualite', 'actualite'), ('politique', 'politique'), ('international', 'international'), ('business', 'business'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('societe', 'societe'), ('spiritualite', 'spiritualite'), ('evenement', 'evenement'), ('video', 'video')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('autres', 'autres'), ('tennis', 'tennis'), ('basket', 'basket'), ('foot', 'foot'), ('lamb', 'lamb')], max_length=250, null=True),
        ),
    ]
