# Generated by Django 3.2.9 on 2023-10-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20231020_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('culture', 'culture'), ('societe', 'societe'), ('sport', 'sport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('spectacles', 'spactacles'), ('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('actualite', 'actualite'), ('societe', 'societe'), ('breaking', 'breaking'), ('sport', 'sport'), ('politique', 'politique'), ('spiritualite', 'spiritualite'), ('video', 'video'), ('evenement', 'evenement'), ('business', 'business'), ('international', 'international'), ('activite', 'activite'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('culture', 'culture')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('basket', 'basket'), ('lamb', 'lamb'), ('foot', 'foot'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
