# Generated by Django 3.2.9 on 2023-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20231026_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('societe', 'societe'), ('sport', 'sport'), ('culture', 'culture'), ('activite', 'activite')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('spectacles', 'spactacles'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('spiritualite', 'spiritualite'), ('evenement', 'evenement'), ('sport', 'sport'), ('actualite', 'actualite'), ('culture', 'culture'), ('video', 'video'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('breaking', 'breaking'), ('event', 'event'), ('business', 'business'), ('pub', 'pub'), ('societe', 'societe'), ('activite', 'activite'), ('international', 'international'), ('politique', 'politique')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('autres', 'autres'), ('lamb', 'lamb'), ('foot', 'foot'), ('basket', 'basket')], max_length=250, null=True),
        ),
    ]
