# Generated by Django 3.2.9 on 2023-10-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20231026_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('activite', 'activite'), ('culture', 'culture'), ('sport', 'sport'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('spectacles', 'spactacles'), ('visites', 'visites'), ('coup de coeur', 'coup de coeur'), ('sorties', 'sorties')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('actualite', 'actualite'), ('politique', 'politique'), ('societe', 'societe'), ('evenement', 'evenement'), ('video', 'video'), ('culture', 'culture'), ('breaking', 'breaking'), ('sport', 'sport'), ('international', 'international'), ('spiritualite', 'spiritualite'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('business', 'business'), ('activite', 'activite'), ('pub', 'pub'), ('event', 'event')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('basket', 'basket'), ('autres', 'autres'), ('lamb', 'lamb'), ('foot', 'foot'), ('tennis', 'tennis')], max_length=250, null=True),
        ),
    ]
