# Generated by Django 3.2.9 on 2023-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20231026_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comment_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('societe', 'societe'), ('culture', 'culture'), ('sport', 'sport'), ('activite', 'activite')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('coup de coeur', 'coup de coeur'), ('sorties', 'sorties'), ('spectacles', 'spactacles'), ('visites', 'visites')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('politique', 'politique'), ('actualite', 'actualite'), ('sport', 'sport'), ('breaking', 'breaking'), ('spiritualite', 'spiritualite'), ('evenement', 'evenement'), ('activite', 'activite'), ('culture', 'culture'), ('event', 'event'), ('video', 'video'), ('business', 'business'), ('pub', 'pub'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('international', 'international'), ('societe', 'societe')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('lamb', 'lamb'), ('basket', 'basket'), ('foot', 'foot'), ('tennis', 'tennis'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
