# Generated by Django 3.2.9 on 2023-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20231026_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='comment_num',
            new_name='comments_num',
        ),
        migrations.AlterField(
            model_name='a_voir',
            name='categorie',
            field=models.CharField(choices=[('culture', 'culture'), ('sport', 'sport'), ('activite', 'activite'), ('societe', 'societe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='i_d',
            field=models.CharField(blank=True, choices=[('visites', 'visites'), ('sorties', 'sorties'), ('coup de coeur', 'coup de coeur'), ('spectacles', 'spactacles')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_categorie',
            field=models.CharField(blank=True, choices=[('business', 'business'), ('politique', 'politique'), ('evenement', 'evenement'), ('international', 'international'), ('activite', 'activite'), ('video', 'video'), ('culture', 'culture'), ('actualite', 'actualite'), ('pub', 'pub'), ('sport', 'sport'), ('spiritualite', 'spiritualite'), ('homme_de_la_semaine', 'homme_de_la_semaine'), ('societe', 'societe'), ('event', 'event'), ('breaking', 'breaking')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='i_d',
            field=models.CharField(blank=True, choices=[('tennis', 'tennis'), ('foot', 'foot'), ('basket', 'basket'), ('lamb', 'lamb'), ('autres', 'autres')], max_length=250, null=True),
        ),
    ]
